import "./globals.css";

export const metadata = {
  title: "LandTick App",
  description: "Generated by create next app",
};

import { Providers } from "./providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
